### ISSUE TITLE
how to run the code ?

### ISSUE THREAD

**Issue by shipeng-liu** [LyapunovJingci/WarehouseRobotPathPlanning#1]

**Comment by LyapunovJingci** [comment]
Hi! Thank you for your interest to this project.
After cloning this project, please first change line 45 in warehouse_test.py and line 17 in RLBrain.py to your own file path. Then run file warehouse_test.py to see the simulation.

**Comment by shipeng-liu** [comment]
I cloned your new code, and I found the same problem as follows：
File "c:\Users\efeff\Desktop\Warehouse_Robot_Path_Planning-master\RL_brain_Robo1.py", line 23, in __init__ 
    f = open(RLBrain.FILEPATH + '\q_table1.txt', 'rb')
I cannot found this file in your repository, where is the q_table1.txt?

**Comment by LyapunovJingci** [comment]
My bad. I just upload them. Thank you!

**Comment by shipeng-liu** [comment]
Thank you! one more question, if I want to retrain the Q-table, should I change the currentstate to state0 and then state1 so as to state2?

**Comment by LyapunovJingci** [comment]
State 0 corresponds to training the map
State 1 corresponds to training the robots to return to the starting point
State 2 corresponds to training the robots to reach the target
These three states follow the three training steps in the flow chart in Readme.
Thanks!

**Comment by shipeng-liu** [comment]
I'm sorry, I am a little puzzled, then how to test the trained network?
